[package]
name = "usage-display"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
embassy-executor = "0.10.0"
embassy-net = { version = "0.9.1", default-features = false, features = ["dhcpv4", "tcp", "dns", "udp"] }
embassy-time = "0.5.0"
embedded-io-async = "0.7.0"
embedded-graphics = "0.8.1"
ssd1306 = "0.10.0"
display-interface = "0.5.0"
esp-alloc = { version = "0.11.0", features = ["esp32s3"] }
esp-bootloader-esp-idf = { version = "0.6.0", features = ["esp32s3"] }
esp-hal = { version = "1.2.2", features = ["esp32s3", "unstable"] }
esp-println = { version = "0.18.0", default-features = false, features = ["esp32s3", "uart"] }
esp-radio = { version = "1.0.0-beta.1", features = ["esp32s3", "wifi", "esp-alloc"] }
heapless = "0.9.2"
esp-rtos = { version = "0.4.0", features = ["esp32s3", "embassy", "esp-radio", "esp-alloc"] }
static_cell = "2.1.0"
reqwless = { git = "https://github.com/drogue-iot/reqwless.git", rev = "b761705cc654e6f31bc064183e219aa09b33968a", default-features = false, features = ["mbedtls-rs"] }
mbedtls-rs = { version = "0.1.0", features = ["embassy-time", "hook-wall-clock"] }
serde = { version = "1.0.228", default-features = false, features = ["derive"] }
serde-json-core = "0.6.0"
time = { version = "0.3", default-features = false }

[profile.dev]
opt-level = "s"

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
panic = "abort"
