[package]
name = "usage-display"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
esp-hal = { version = "1.2.2", features = ["esp32s3"] }
esp-bootloader-esp-idf = { version = "0.4.0", features = ["esp32s3"] }
esp-radio = { version = "1.0.0-beta.1", features = ["esp32s3", "wifi"] }

[profile.dev]
opt-level = "s"

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
panic = "abort"
