[build]
target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core", "alloc"]

[target.xtensa-esp32s3-none-elf]
rustflags = [
  "-C", "link-arg=-Wl,-Tlinkall.x",
  "-C", "link-arg=-Wl,--undefined=esp_app_desc",
  "-C", "link-arg=-nostartfiles",
]
